# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# enable colors in ls
export CLICOLOR=1

# Load aliases
[[ -r ~/.aliases ]] && . ~/.aliases

# Add Python to path
export PATH=$(brew --prefix python)/bin:$(brew --prefix python)/libexec/bin:$PATH

# Add Rust to path
export PATH=$(brew --prefix rustup)/bin:$PATH

# Add my dotfiles/bin to path
export PATH=$HOME/Projects/github/dotfiles/bin:$PATH

# Load Oh My Posh
eval "$(oh-my-posh init zsh)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
